name: Node CI

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 8.x, 10.x, 12.x ]

    steps:
    - name: Checkout project
      uses: actions/checkout@v1
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Test Server
      working-directory: ${{ github.workspace }}/Final/Server
      run: |
        npm run CiTest
        
    - name: test Client
      working-directory: ${{ github.workspace }}/Final/Client
      run: |
        npm run CiTest
      
      env:
        CI: true
